# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
       Symfony\Component\Security\Core\User\User: plaintext

    providers:
        my_users:
            memory:
               users:
                  adrien:
                      password: adrien
                      roles: ['ROLE_ADMIN']
                  foo:
                      password: bar
                      roles: ['ROLE_USER']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: my_users
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
        - {path: '^/form', roles: ['ROLE_ADMIN', 'ROLE_USER']}