# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  app.abstract_youtube_fetcher:
    abstract: true
    arguments: ['@mailer']


  app.youtube_fetcher_without_logger:
    class: AppBundle\Youtube\YoutubeFetcher
    parent: app.abstract_youtube_fetcher

  app.youtube_fetcher_with_logger:
    class: AppBundle\Youtube\YoutubeFetcher
    parent: app.abstract_youtube_fetcher
    calls:
      - [setLogger, ['@logger']]

  app.youtube_fetcher:
    alias: app.youtube_fetcher_without_logger
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
